apiVersion: 1
datasources:
  - name: MeteoLogger PostgreSQL
    uid: meteologger_pg
    type: postgres
    access: proxy
    url: db:5432
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      minInterval: "1m"
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
